version: '2'
services:
  postgres-star:
    image: postgres
    container_name: postgres-star
    expose:
      - "5432"
    volumes:
      - /var/lib/docker/jenkins_devops/sonar-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  sonarqube-star:
    image: sonarqube-star
    container_name: sonarqube-star
    ports:
      - "9000:9000"
      - "9002:9002"
    links:
      - postgres-star
    volumes:
      - /var/lib/docker/jenkins_devops/sonar-data:/opt/sonarqube/data
      - /var/lib/docker/jenkins_devops/sonar-extensions:/opt/sonarqube/extensions
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres-star:5432/sonar
